// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKNREEJTql3ANrqGjcPR6f0GEFO0kPthE',
    appId: '1:997146501960:web:4ca26e2ac896d82d3b097d',
    messagingSenderId: '997146501960',
    projectId: 'kigali-directory-bc296',
    authDomain: 'kigali-directory-bc296.firebaseapp.com',
    storageBucket: 'kigali-directory-bc296.firebasestorage.app',
    measurementId: 'G-YG3VM84WWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tADWzcEwv6wpHhZPNoRZOJ6idUOLeVM',
    appId: '1:997146501960:android:2c928469e4ae55823b097d',
    messagingSenderId: '997146501960',
    projectId: 'kigali-directory-bc296',
    storageBucket: 'kigali-directory-bc296.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX0R8jXMxVx0qKQ_Az8oKCjuZA-ct4K3s',
    appId: '1:997146501960:ios:9a2d6775e35a36e93b097d',
    messagingSenderId: '997146501960',
    projectId: 'kigali-directory-bc296',
    storageBucket: 'kigali-directory-bc296.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX0R8jXMxVx0qKQ_Az8oKCjuZA-ct4K3s',
    appId: '1:997146501960:ios:9a2d6775e35a36e93b097d',
    messagingSenderId: '997146501960',
    projectId: 'kigali-directory-bc296',
    storageBucket: 'kigali-directory-bc296.firebasestorage.app',
    iosBundleId: 'com.example.kigaliCityServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKNREEJTql3ANrqGjcPR6f0GEFO0kPthE',
    appId: '1:997146501960:web:2f30195582d261cd3b097d',
    messagingSenderId: '997146501960',
    projectId: 'kigali-directory-bc296',
    authDomain: 'kigali-directory-bc296.firebaseapp.com',
    storageBucket: 'kigali-directory-bc296.firebasestorage.app',
    measurementId: 'G-T8BGDGLTNZ',
  );
}
